# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5001b4a23e82e020fb519097159dccf9396d5e7872e37b414b8c30f85d8844256411533b23fdb989073fba1813234fdf35f3d269f062f87b6f625cf866a6fba8

test:
  secret_key_base: 858fb200913a99cf78a5b7c7a20ddfff5da5e1e2a8533cc2809d15bf0476bc2c4e2c7e86825ecbe8ccd953240ed32c0f56145771bfbac91645aa9e8121d6ff90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
